### ISSUE TITLE
mkdoc serve exception

### ISSUE THREAD

**Issue by ShadySQL** [PagerDuty/incident-response-docs#25]
I'am gonna look into this but this is NOT working.

mkdocs serve
INFO    -  Building documentation... 
INFO    -  Cleaning site directory 
WARNING -  Template variable warning: 'site_name' is being deprecated and will not be available in a future version. Use 'config.site_name' instead. 
WARNING -  Template variable warning: 'favicon' is being deprecated and will not be available in a future version. Use '{{ base_url }}/img/favicon.ico' instead. 
WARNING -  Template variable warning: 'repo_url' is being deprecated and will not be available in a future version. Use 'config.repo_url' instead. 
WARNING -  Template variable warning: 'page_title' is being deprecated and will not be available in a future version. Use 'page.title' instead. 
WARNING -  Template variable warning: 'canonical_url' is being deprecated and will not be available in a future version. Use 'page.canonical_url' instead. 
WARNING -  Template variable warning: 'page_description' is being deprecated and will not be available in a future version. Use 'config.site_description' instead. 
WARNING -  Template variable warning: 'copyright' is being deprecated and will not be available in a future version. Use 'config.copyright' instead. 
WARNING -  Template variable warning: 'site_url' is being deprecated and will not be available in a future version. Use 'config.site_url' instead. 
WARNING -  Template variable warning: 'content' is being deprecated and will not be available in a future version. Use 'page.content' instead. 
WARNING -  Template variable warning: 'site_author' is being deprecated and will not be available in a future version. Use 'config.site_author' instead. 
WARNING -  Template variable warning: 'google_analytics' is being deprecated and will not be available in a future version. Use 'config.google_analytics' instead. 
WARNING -  Template variable warning: 'repo_name' is being deprecated and will not be available in a future version. Use 'config.repo_name' instead. 
WARNING -  Template variable warning: 'current_page' is being deprecated and will not be available in a future version. Use 'page' instead. 
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mkdocs/__main__.py", line 127, in serve_command
    livereload=livereload
  File "/usr/local/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 82, in serve
    config = builder()
  File "/usr/local/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 78, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/usr/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 379, in build
    build_pages(config, dirty=dirty)
  File "/usr/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 306, in build_pages
    build_template('404.html', env, config, site_navigation)
  File "/usr/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 166, in build_template
    output_content = template.render(context)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tester/Documents/incident-response-docs/theme/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/tester/Documents/incident-response-docs/theme/base.html", line 119, in top-level template code
    {% include "drawer.html" %}
  File "/Users/tester/Documents/incident-response-docs/theme/drawer.html", line 53, in top-level template code
    {% include "nav.html" %}
  File "/usr/local/lib/python2.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: nav.html

**Comment by richadams** [comment]
This is because the latest version of `mkdocs-material` introduced breaking changes. You should be using version 0.2.4. I updated our `.travis.yml`, but forgot to update the README. I'll update that now. Sorry about that!

`pip install mkdocs-material==0.2.4`
